<h1>Video Manipulation</h1>
Multiple types of video manipulation based on recieved type of symptoms
1. pixel value filter
2. 

In [1]:
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt
import sys
# os.environ['CUDA_VISIBLE_DEVICES'] = '2'

In [2]:
img = cv2.imread('random.jpg')
print(img[:,:,2])

[[235 235 235 ... 235 235 235]
 [238 238 238 ... 238 238 238]
 [243 243 243 ... 243 243 243]
 ...
 [249 249 249 ... 248 248 248]
 [249 249 249 ... 248 248 248]
 [250 250 250 ... 248 248 248]]


In [3]:
############## HYPERPARAMETERS ###############
VALUE_THRESHOLD = 200

In [4]:
cap = cv2.VideoCapture(0)
while(True):
    ret, frame = cap.read()
    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    hsv[(hsv[:,:,2] > VALUE_THRESHOLD)] = VALUE_THRESHOLD
#     hsv[hsv > VALUE_THRESHOLD] = VALUE_THRESHOLD
    frame = cv2.cvtColor(hsv,cv2.COLOR_HSV2BGR)
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()
    

IndexError: too many indices for array